config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'

  resources :profiles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/profile.rb
class Profile < ApplicationRecord
  validates :avatar, presence: true
  belongs_to :user
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tweets
  has_one :profile
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/concerns/home_controller.rb
class HomeController < ApplicationController

  def index
    @brand = 'Twitter'
    @tweets = Tweet.all
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  def index
    @profiles = Profile.all
  end

  def new 
    @profile = Profile.new
  end

  def show
  end

  def create
    @profile = Profile.new(profile_params)
    # creating an empty instance and fill it with details
    @profile.user = current_user

    # sending back a response from the person who used the form
    respond_to do |format|
      # save profile
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created'}
      else
        format.html { render :new}
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      # save profile
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated'}
      else
        format.html { render :edit}
      end
    end
  end

  def destroy
    respond_to do |format|
      if @profile.destroy
        format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed'}
      end
    end
  end

  private

  def profile_params
    params.require(:profile).permit(:avatar, :first_name, :last_name, :country)
  end

  def set_profile
    @profile = Profile.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h1><%= @brand %></h1>

<ul>
  <% @tweets.each do |tweet| %>
    <li><%= tweet.message %> | <%= tweet.user.email unless tweet.user.nil? %> </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwitterClone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <% if user_signed_in? %>
        <%= link_to('Logout', destroy_user_session_path, method: :delete) %>        
      <% else %>
        <%= link_to('Login', new_user_session_path)  %>  
      <% end %>
    </nav>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/profiles/_form.html.erb
 <%= form_with(model: @profile, local: true) do |form| %>


  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>
  
      <ul>
      <% @profile.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div>
    <%= form.label :avatar%>
    <%= form.text_field :avatar, id: :avatar%>
  </div>

  <div>
    <%= form.label :first_name%>
    <%= form.text_field :first_name, id: :first_name%>
  </div>

  <div>
    <%= form.label :last_name%>
    <%= form.text_field :last_name, id: :last_name%>
  </div>

  <div>
    <%= form.label :country%>
    <%= form.text_field :country, id: :country%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<%end%>

app/views/profiles/edit.html.erb
<h1>Edit</h1>

<%= link_to 'back', profiles_path %>

<%= render 'form', profile: @profile %>

app/views/profiles/index.html.erb
<h1>Index</h1>
<%= link_to 'create', new_profile_path %>

<ul>
  <% @profiles.each do |profile| %>
    <li><%= profile.first_name %> | 
    <%= link_to 'show', profile_path(profile) %> | 
    <%= link_to 'edit', edit_profile_path(profile) %></li>
  <% end %>
</ul>

app/views/profiles/new.html.erb
<h1>New</h1>

<%= link_to 'back', profiles_path %>

<%= render 'form', profile: @profile %>

app/views/profiles/show.html.erb
<h1>Show Profile</h1>

<%= image_tag @profile.avatar, width: 200 %>
<%= @profile.first_name%>  <%= @profile.last_name%> | 
<%= link_to 'edit', edit_profile_path(@profile) %> | 
<%= link_to 'back', profiles_path %> | 
<%= link_to 'delete', profile_path(@profile), method: :delete, data: { confirm: 'Are you sure'
} %> 